# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [3]:
# import the relevant libraries
import pandas as pd
import numpy as np

## Load the data

In [6]:
# load the preprocessed CSV data
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [8]:
# eyeball the data
data_preprocessed.head()

loop_1  loop_2  loop_3  loop_4  ID  Month_value  weekday  \
0    True   False   False   False  11            7        1   
1   False   False    True   False  36            7        1   
2    True   False   False   False   3            7        2   
3    True   False   False   False   7            7        3   
4    True   False   False   False  11            7        3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Reason for Absence  
0                  26  
1                   0  
2                  23  
3                   7  
4                  23

## Create the targets

In [11]:
# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [13]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us
# alternatively, if we had more data, we could have found other ways to deal with the issue 
# for instance, we could have assigned some arbitrary value as a cut-off line, instead of the median

# note that what line does is to assign 1 to anyone who has been absent 4 hours or more (more than 3 hours)
# that is the equivalent of taking half a day off

# initial code from the lecture
# targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

# parameterized code
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [15]:
# eyeball the targets
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [17]:
# create a Series in the original data frame that will contain the targets for the regression
data_preprocessed['Excessive Absenteeism'] = targets

In [19]:
# check what happened
# maybe manually see how the targets were created
data_preprocessed.head()

loop_1  loop_2  loop_3  loop_4  ID  Month_value  weekday  \
0    True   False   False   False  11            7        1   
1   False   False    True   False  36            7        1   
2    True   False   False   False   3            7        2   
3    True   False   False   False   7            7        3   
4    True   False   False   False  11            7        3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Reason for Absence  Excessive Absenteeism  
0                  26                      1  
1                   0                      0  
2                  23                      0  
3                   7                      1  
4                  23                      0

## A comment on the targets

In [22]:
# check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array
targets.sum() / targets.shape[0]

0.45571428571428574

In [24]:
# create a checkpoint by dropping the unnecessary variables
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [26]:
# check if the line above is a checkpoint :)

# if data_with_targets is data_preprocessed = True, then the two are pointing to the same object
# if it is False, then the two variables are completely different and this is in fact a checkpoint
data_with_targets is data_preprocessed

False

In [28]:
# check what's inside
data_with_targets.head()

loop_1  loop_2  loop_3  loop_4  ID  Month_value  weekday  \
0    True   False   False   False  11            7        1   
1   False   False    True   False  36            7        1   
2    True   False   False   False   3            7        2   
3    True   False   False   False   7            7        3   
4    True   False   False   False  11            7        3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Reason for Absence  \
0               30          0         2     1                  26   
1               31          0         1     0                   0   
2               31          0         0     0                  23   
3               24          0         2     0                   7   
4               30          0         2     1                  23   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for the regression

In [31]:
data_with_targets.shape

(700, 17)

In [33]:
# selects all rows and all columns until 14 (excluding)
data_with_targets.iloc[:,:14]

loop_1  loop_2  loop_3  loop_4  ID  Month_value  weekday  \
0      True   False   False   False  11            7        1   
1     False   False    True   False  36            7        1   
2      True   False   False   False   3            7        2   
3      True   False   False   False   7            7        3   
4      True   False   False   False  11            7        3   
..      ...     ...     ...     ...  ..          ...      ...   
695   False    True   False   False  17            5        2   
696    True   False   False   False  28            5        2   
697    True   False   False   False  18            5        3   
698    True   False   False   False  25            5        3   
699   False    True   False   False  15            5        3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  
0                 30          0         2  
1                 31          0         1  
2                 31          0         0  
3                 24          0         2  
4                 30          0         2  
..               ...        ...       ...  
695               22          1         2  
696               24          0         1  
697               25          1         0  
698               25          1         0  
699               25          0         1  

[700 rows x 14 columns]

In [35]:
# selects all rows and all columns but the last one (basically the same operation)
data_with_targets.iloc[:,:-1]

loop_1  loop_2  loop_3  loop_4  ID  Month_value  weekday  \
0      True   False   False   False  11            7        1   
1     False   False    True   False  36            7        1   
2      True   False   False   False   3            7        2   
3      True   False   False   False   7            7        3   
4      True   False   False   False  11            7        3   
..      ...     ...     ...     ...  ..          ...      ...   
695   False    True   False   False  17            5        2   
696    True   False   False   False  28            5        2   
697    True   False   False   False  18            5        3   
698    True   False   False   False  25            5        3   
699   False    True   False   False  15            5        3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Reason for Absence  
0                 30          0         2     1                  26  
1                 31          0         1     0                   0  
2                 31          0         0     0                  23  
3                 24          0         2     0                   7  
4                 30          0         2     1                  23  
..               ...        ...       ...   ...                 ...  
695               22          1         2     0                  10  
696               24          0         1     2                   6  
697               25          1         0     0                  10  
698               25          1         0     0                  23  
699               25          0         1     1                  28  

[700 rows x 16 columns]

In [37]:
# create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [40]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
absenteeism_scaler = StandardScaler()

In [42]:
# fit the unscaled_inputs
# this basically calculates the mean and standard deviation of each feature
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [44]:
# transform the unscaled inputs
# this is the scaling itself - we subtract the mean and divide by the standard deviation
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [46]:
# eyeball the newly created variable
scaled_inputs

array([[ 0.60595998, -0.43643578, -0.33333333, ...,  0.88046927,
         0.26848661,  0.78902009],
       [-1.65027399, -0.43643578,  3.        , ..., -0.01928035,
        -0.58968976, -2.32463248],
       [ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
        -0.58968976,  0.42975249],
       ...,
       [ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
        -0.58968976, -1.1270738 ],
       [ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
        -0.58968976,  0.42975249],
       [-1.65027399,  2.29128785, -0.33333333, ..., -0.01928035,
         0.26848661,  1.02853183]])

In [48]:
# check the shape of the array
scaled_inputs.shape

(700, 16)

## Split the data into train & test and shuffle

### Import the relevant module

In [52]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

### Split

In [55]:
# check how this method works
train_test_split(scaled_inputs, targets)

[array([[ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
         -0.58968976,  0.42975249],
        [ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
         -0.58968976,  1.02853183],
        [ 0.60595998, -0.43643578, -0.33333333, ..., -0.01928035,
          1.12666297,  0.42975249],
        ...,
        [ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
         -0.58968976,  1.02853183],
        [ 0.60595998, -0.43643578, -0.33333333, ..., -0.01928035,
          1.12666297, -1.00731793],
        [ 0.60595998, -0.43643578, -0.33333333, ..., -0.01928035,
          1.12666297, -0.76780619]]),
 array([[ 0.60595998, -0.43643578, -0.33333333, ...,  1.78021889,
         -0.58968976,  0.30999662],
        [ 0.60595998, -0.43643578, -0.33333333, ..., -0.91902997,
         -0.58968976,  1.02853183],
        [ 0.60595998, -0.43643578, -0.33333333, ...,  0.88046927,
         -0.58968976, -2.32463248],
        ...,
        [ 0.60595998, -0.43643578, -0.33333333, ..., -

In [57]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [59]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 16) (560,)


In [61]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 16) (140,)


## Logistic regression with sklearn

In [64]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

### Training the model

In [67]:
# create a logistic regression object
reg = LogisticRegression()

In [69]:
# fit our train inputs
# that is basically the whole training part of the machine learning
reg.fit(x_train,y_train)

LogisticRegression()

In [71]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.7071428571428572

### Manually check the accuracy

In [74]:
# find the model outputs according to our model
model_outputs = reg.predict(x_train)
model_outputs

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,

In [76]:
# compare them with the targets
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [78]:
# ACTUALLY compare the two variables
model_outputs == y_train

array([ True, False, False, False,  True, False,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False, False, False,  True,
        True, False, False,  True,  True,  True, False, False,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [80]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

396

In [82]:
# get the total number of instances
model_outputs.shape[0]

560

In [84]:
# calculate the accuracy of the model
# divide the number of correctly predicted outputs by the number of all outputs
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7071428571428572

### Finding the intercept and coefficients

In [87]:
# get the intercept (bias) of our model
reg.intercept_

array([-0.18897929])

In [89]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 0.13013114,  0.01504055, -0.16230368, -0.15728387, -0.33713527,
         0.11892486, -0.14393016,  0.45119032, -0.20788577,  0.20192958,
         0.06612214, -0.03285815, -0.0983186 ,  0.31043052, -0.13102497,
        -0.41970787]])

In [91]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['loop_1', 'loop_2', 'loop_3', 'loop_4', 'ID', 'Month_value',
       'weekday', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Reason for Absence'], dtype=object)

In [93]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [95]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0                    loop_1     0.130131
1                    loop_2     0.015041
2                    loop_3    -0.162304
3                    loop_4    -0.157284
4                        ID    -0.337135
5               Month_value     0.118925
6                   weekday    -0.143930
7    Transportation Expense     0.451190
8          Distance to Work    -0.207886
9                       Age     0.201930
10  Daily Work Load Average     0.066122
11          Body Mass Index    -0.032858
12                Education    -0.098319
13                 Children     0.310431
14                     Pets    -0.131025
15       Reason for Absence    -0.419708

In [97]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.188979
1                    loop_1     0.130131
2                    loop_2     0.015041
3                    loop_3    -0.162304
4                    loop_4    -0.157284
5                        ID    -0.337135
6               Month_value     0.118925
7                   weekday    -0.143930
8    Transportation Expense     0.451190
9          Distance to Work    -0.207886
10                      Age     0.201930
11  Daily Work Load Average     0.066122
12          Body Mass Index    -0.032858
13                Education    -0.098319
14                 Children     0.310431
15                     Pets    -0.131025
16       Reason for Absence    -0.419708

## Interpreting the coefficients

In [100]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [102]:
# display the df
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.188979    0.827804
1                    loop_1     0.130131    1.138978
2                    loop_2     0.015041    1.015154
3                    loop_3    -0.162304    0.850183
4                    loop_4    -0.157284    0.854461
5                        ID    -0.337135    0.713812
6               Month_value     0.118925    1.126285
7                   weekday    -0.143930    0.865948
8    Transportation Expense     0.451190    1.570180
9          Distance to Work    -0.207886    0.812300
10                      Age     0.201930    1.223762
11  Daily Work Load Average     0.066122    1.068357
12          Body Mass Index    -0.032858    0.967676
13                Education    -0.098319    0.906360
14                 Children     0.310431    1.364012
15                     Pets    -0.131025    0.877196
16       Reason for Absence    -0.419708    0.657239

In [104]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
8    Transportation Expense     0.451190    1.570180
14                 Children     0.310431    1.364012
10                      Age     0.201930    1.223762
1                    loop_1     0.130131    1.138978
6               Month_value     0.118925    1.126285
11  Daily Work Load Average     0.066122    1.068357
2                    loop_2     0.015041    1.015154
12          Body Mass Index    -0.032858    0.967676
13                Education    -0.098319    0.906360
15                     Pets    -0.131025    0.877196
7                   weekday    -0.143930    0.865948
4                    loop_4    -0.157284    0.854461
3                    loop_3    -0.162304    0.850183
0                 Intercept    -0.188979    0.827804
9          Distance to Work    -0.207886    0.812300
5                        ID    -0.337135    0.713812
16       Reason for Absence    -0.419708    0.657239